[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clippy]
toolchain = "beta"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]

[tasks.doc]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = ["doc", "-p", "tighterror", "--all-features", "--no-deps", "--open"]

[tasks.docb]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = [
    "doc",
    "-p",
    "tighterror-build",
    "--all-features",
    "--no-deps",
    "--open",
]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
