[config]
default_to_workspace = false

[tasks.build]
dependencies = ["tb-errors"]
args = ["build", "--workspace", "--all-features"]

[tasks.test]
args = ["test", "--workspace", "--all-features"]

[tasks.clippy]
clear = true
dependencies = ["clippy-workspace", "clippy-compilation-tests"]

[tasks.clippy-workspace]
toolchain = "beta"
command = "cargo"
args = ["clippy", "--workspace", "--all-features", "--all-targets"]

[tasks.clippy-compilation-tests]
toolchain = "beta"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]
cwd = "crates/tighterror-build/tests/compilation"

[tasks.tb-errors]
condition = { files_modified = { input = [
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/crates/tighterror-build/tighterror.yaml",
], output = [
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/crates/tighterror-build/src/errors.rs",
] } }
run_task = "gen-tb-errors"

[tasks.gen-tb-errors]
dependencies = ["ct"]
cwd = "crates/tighterror-build"
command = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug/cargo-tighterror"
args = ["tighterror"]

[tasks.up]
cwd = "crates/tighterror-build"
command = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug/cargo-tighterror"
args = ["tighterror", "--update"]

[tasks.ct]
command = "cargo"
args = ["build", "-p", "cargo-tighterror"]

[tasks.doc]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = ["doc", "-p", "tighterror", "--all-features", "--no-deps", "--open"]

[tasks.docb]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = [
    "doc",
    "-p",
    "tighterror-build",
    "--all-features",
    "--no-deps",
    "--open",
]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.purge]
script = """
find . -type d -name target | xargs rm -rf
find crates/tighterror-build/tests -type f -name Cargo.lock | xargs rm -f
"""

[tasks.extra_tests_implicit_category_toml_build]
cwd = "crates/tighterror-build/tests/implicit_category_toml"
command = "cargo"
args = ["build"]

[tasks.extra_tests_implicit_category_toml_test]
cwd = "crates/tighterror-build/tests/implicit_category_toml"
command = "cargo"
args = ["test", "--all-features", "--all-targets"]

[tasks.extra_tests_implicit_category_toml_clippy]
cwd = "crates/tighterror-build/tests/implicit_category_toml"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]

[tasks.extra_tests_implicit_category_toml_rustfmt]
cwd = "crates/tighterror-build/tests/implicit_category_toml"
command = "cargo"
args = ["fmt", "--check"]

[tasks.extra_tests_minimal_build]
cwd = "crates/tighterror-build/tests/minimal"
command = "cargo"
args = ["build"]

[tasks.extra_tests_minimal_test]
cwd = "crates/tighterror-build/tests/minimal"
command = "cargo"
args = ["test", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_clippy]
cwd = "crates/tighterror-build/tests/minimal"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_rustfmt]
cwd = "crates/tighterror-build/tests/minimal"
command = "cargo"
args = ["fmt", "--check"]

[tasks.extra_tests_minimal_256_variants_build]
cwd = "crates/tighterror-build/tests/minimal_256_variants"
command = "cargo"
args = ["build"]

[tasks.extra_tests_minimal_256_variants_test]
cwd = "crates/tighterror-build/tests/minimal_256_variants"
command = "cargo"
args = ["test", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_256_variants_clippy]
cwd = "crates/tighterror-build/tests/minimal_256_variants"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_256_variants_rustfmt]
cwd = "crates/tighterror-build/tests/minimal_256_variants"
command = "cargo"
args = ["fmt", "--check"]

[tasks.extra_tests_minimal_toml_build]
cwd = "crates/tighterror-build/tests/minimal_toml"
command = "cargo"
args = ["build"]

[tasks.extra_tests_minimal_toml_test]
cwd = "crates/tighterror-build/tests/minimal_toml"
command = "cargo"
args = ["test", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_toml_clippy]
cwd = "crates/tighterror-build/tests/minimal_toml"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_toml_rustfmt]
cwd = "crates/tighterror-build/tests/minimal_toml"
command = "cargo"
args = ["fmt", "--check"]

[tasks.extra_tests_minimal_with_display_build]
cwd = "crates/tighterror-build/tests/minimal_with_display"
command = "cargo"
args = ["build"]

[tasks.extra_tests_minimal_with_display_test]
cwd = "crates/tighterror-build/tests/minimal_with_display"
command = "cargo"
args = ["test", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_with_display_clippy]
cwd = "crates/tighterror-build/tests/minimal_with_display"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_with_display_rustfmt]
cwd = "crates/tighterror-build/tests/minimal_with_display"
command = "cargo"
args = ["fmt", "--check"]

[tasks.extra_tests_compilation_build]
cwd = "crates/tighterror-build/tests/compilation"
command = "cargo"
args = ["build"]

[tasks.extra_tests_compilation_test]
cwd = "crates/tighterror-build/tests/compilation"
command = "cargo"
args = ["test", "--all-features", "--all-targets"]

[tasks.extra_tests_compilation_clippy]
cwd = "crates/tighterror-build/tests/compilation"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]

[tasks.extra_tests_compilation_inner_rustfmt]
script = """
cargo fmt -- --check crates/tighterror-build/tests/compilation/tests/compile-fail/*.rs
"""

[tasks.extra_tests_compilation_rustfmt]
dependencies = ["extra_tests_compilation_inner_rustfmt"]
cwd = "crates/tighterror-build/tests/compilation"
command = "cargo"
args = ["fmt", "--check"]

[tasks.extra_tests_minimal_no_std_build]
cwd = "crates/tighterror-build/tests/minimal_no_std"
command = "cargo"
args = ["build"]

[tasks.extra_tests_minimal_no_std_test]
cwd = "crates/tighterror-build/tests/minimal_no_std"
command = "cargo"
args = ["test", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_no_std_clippy]
cwd = "crates/tighterror-build/tests/minimal_no_std"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]

[tasks.extra_tests_minimal_no_std_rustfmt]
cwd = "crates/tighterror-build/tests/minimal_no_std"
command = "cargo"
args = ["fmt", "--check"]

[tasks.et_build]
dependencies = [
    "extra_tests_implicit_category_toml_build",
    "extra_tests_minimal_build",
    "extra_tests_minimal_256_variants_build",
    "extra_tests_minimal_toml_build",
    "extra_tests_minimal_with_display_build",
    "extra_tests_compilation_build",
    "extra_tests_minimal_no_std_build",
]

[tasks.et_test]
dependencies = [
    "extra_tests_implicit_category_toml_test",
    "extra_tests_minimal_test",
    "extra_tests_minimal_256_variants_test",
    "extra_tests_minimal_toml_test",
    "extra_tests_minimal_with_display_test",
    # "extra_tests_compilation_test", -- !! must be run separately !!
    "extra_tests_minimal_no_std_test",
]

[tasks.et_clippy]
dependencies = [
    "extra_tests_implicit_category_toml_clippy",
    "extra_tests_minimal_clippy",
    "extra_tests_minimal_256_variants_clippy",
    "extra_tests_minimal_toml_clippy",
    "extra_tests_minimal_with_display_clippy",
    "extra_tests_compilation_clippy",
    "extra_tests_minimal_no_std_clippy",
]

[tasks.et_fmt]
dependencies = [
    "extra_tests_implicit_category_toml_rustfmt",
    "extra_tests_minimal_rustfmt",
    "extra_tests_minimal_256_variants_rustfmt",
    "extra_tests_minimal_toml_rustfmt",
    "extra_tests_minimal_with_display_rustfmt",
    "extra_tests_compilation_rustfmt",
    "extra_tests_minimal_no_std_rustfmt",
]

[tasks.et]
dependencies = ["et_fmt", "et_build", "et_test", "et_clippy"]

[tasks.et_all]
dependencies = ["purge", "extra_tests_compilation_test", "et"]
