[config]
default_to_workspace = false

[tasks.build]
args = ["build", "--workspace", "--all-features"]

[tasks.test]
args = ["test", "--workspace", "--all-features"]

[tasks.clippy]
toolchain = "beta"
command = "cargo"
args = ["clippy", "--workspace", "--all-features", "--all-targets"]

[tasks.doc]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = ["doc", "-p", "tighterror", "--all-features", "--no-deps", "--open"]

[tasks.docb]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = [
    "doc",
    "-p",
    "tighterror-build",
    "--all-features",
    "--no-deps",
    "--open",
]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
