[config]
default_to_workspace = false

[tasks.build]
dependencies = ["tb-errors"]
args = ["build", "--workspace", "--all-features"]

[tasks.test]
args = ["test", "--workspace", "--all-features"]

[tasks.clippy]
clear = true
dependencies = ["clippy-workspace", "clippy-compilation-tests"]

[tasks.clippy-workspace]
toolchain = "beta"
command = "cargo"
args = ["clippy", "--workspace", "--all-features", "--all-targets"]

[tasks.clippy-compilation-tests]
toolchain = "beta"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]
cwd = "crates/tighterror-build/tests/compilation"

[tasks.tb-errors]
condition = { files_modified = { input = [
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/crates/tighterror-build/tighterror.yaml",
], output = [
    "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/crates/tighterror-build/src/errors.rs",
] } }
run_task = "gen-tb-errors"

[tasks.gen-tb-errors]
dependencies = ["ct"]
cwd = "crates/tighterror-build"
command = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug/cargo-tighterror"
args = ["tighterror"]

[tasks.up]
cwd = "crates/tighterror-build"
command = "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/target/debug/cargo-tighterror"
args = ["tighterror", "--update"]

[tasks.ct]
command = "cargo"
args = ["build", "-p", "cargo-tighterror"]

[tasks.doc]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = ["doc", "-p", "tighterror", "--all-features", "--no-deps", "--open"]

[tasks.docb]
env = { "RUSTDOCFLAGS" = "--cfg docsrs" }
toolchain = "nightly"
command = "cargo"
args = [
    "doc",
    "-p",
    "tighterror-build",
    "--all-features",
    "--no-deps",
    "--open",
]

[tasks.fmt]
command = "cargo"
args = ["fmt", "--all", "--", "--check"]

[tasks.purge]
script = """
find . -type d -name target | xargs rm -rf
find crates/tighterror-build/tests -type f -name Cargo.lock | xargs rm -f
"""

[tasks.extra_tests_build]
cwd = "crates/tighterror-build/tests/extra"
command = "cargo"
args = ["build", "--workspace"]

[tasks.extra_tests_test]
cwd = "crates/tighterror-build/tests/extra"
command = "cargo"
args = ["test", "--workspace", "--all-features", "--all-targets"]

[tasks.extra_tests_clippy]
cwd = "crates/tighterror-build/tests/extra"
command = "cargo"
args = ["clippy", "--workspace", "--all-features", "--all-targets"]

[tasks.extra_tests_rustfmt]
cwd = "crates/tighterror-build/tests/extra"
command = "cargo"
args = ["fmt", "--check"]

[tasks.extra_tests_compilation_build]
cwd = "crates/tighterror-build/tests/compilation"
command = "cargo"
args = ["build"]

[tasks.extra_tests_compilation_test]
cwd = "crates/tighterror-build/tests/compilation"
command = "cargo"
args = ["test", "--all-features", "--all-targets"]

[tasks.extra_tests_compilation_clippy]
cwd = "crates/tighterror-build/tests/compilation"
command = "cargo"
args = ["clippy", "--all-features", "--all-targets"]

[tasks.extra_tests_compilation_inner_rustfmt]
script = """
cargo fmt -- --check crates/tighterror-build/tests/compilation/tests/compile-fail/*.rs
"""

[tasks.extra_tests_compilation_rustfmt]
dependencies = ["extra_tests_compilation_inner_rustfmt"]
cwd = "crates/tighterror-build/tests/compilation"
command = "cargo"
args = ["fmt", "--check"]

[tasks.et_build]
dependencies = ["extra_tests_build", "extra_tests_compilation_build"]

[tasks.et_test]
alias = "extra_tests_test"

[tasks.et_clippy]
dependencies = ["extra_tests_clippy", "extra_tests_compilation_clippy"]

[tasks.et_fmt]
dependencies = ["extra_tests_rustfmt", "extra_tests_compilation_rustfmt"]

[tasks.et]
dependencies = ["et_fmt", "et_build", "et_test", "et_clippy"]

[tasks.et_all]
dependencies = ["purge", "extra_tests_compilation_test", "et"]
